ACTIONS = {
    'CREATE_CAMPAIGN': 'CREATE_CAMPAIGN',
    'VOTE': 'VOTE',
    'EDIT_CAMPAIGN': 'EDIT_CAMPAIGN',
    'DELETE_CAMPAIGN': 'DELETE_CAMPAIGN',
    'WITHDRAW': 'WITHDRAW',
    'EXECUTE_VOUCHER': 'EXECUTE_VOUCHER',
    'DEPOSIT': 'DEPOSIT',
    'DECREASE_TOKEN': 'DECREASE_TOKEN',
    'CREATE_PROFILE': 'CREATE_PROFILE',
    'UPDATE_PROFILE': 'UPDATE_PROFILE',
    'DELETE_PROFILE': 'DELETE_PROFILE'
}
