NOTIFICATION_ACTIONS = {
    'VOTE': 'VOTE',
    'CREATE_CAMPAIGN': 'CREATE_CAMPAIGN',
    'EDIT_CAMPAIGN': 'EDIT_CAMPAIGN',
    'DELETE_CAMPAIGN': 'DELETE_CAMPAIGN',
    'WITHDRAW': 'WITHDRAW',
    'DEPOSIT': 'DEPOSIT',
    'DECREASE_TOKEN': 'DECREASE_TOKEN',
    'SYSTEM': 'SYSTEM'
}
