server {
  location / {
    proxy_pass http://host.docker.internal:5002;
  }

  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;

  location ~* \.(eot|ttf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
  }
}
